---
abstract: 'The great new Seq!'
author:
  - 'David Raab <davidraab83@gmail.com>'
build_requires:
  Test2::Suite: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Seq
provides:
  Seq:
    file: lib/Seq.pm
    version: '0.001'
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: '0.001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
